Resources:
  sampleTable0D61001F:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      TableName: samples
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: InfraStack/sampleTable/Resource
  sampleLambdaServiceRole07311550:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: InfraStack/sampleLambda/ServiceRole/Resource
  sampleLambdaServiceRoleDefaultPolicy8C711846:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - dynamodb:BatchGetItem
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:Query
              - dynamodb:GetItem
              - dynamodb:Scan
              - dynamodb:BatchWriteItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - sampleTable0D61001F
                  - Arn
              - Ref: AWS::NoValue
        Version: "2012-10-17"
      PolicyName: sampleLambdaServiceRoleDefaultPolicy8C711846
      Roles:
        - Ref: sampleLambdaServiceRole07311550
    Metadata:
      aws:cdk:path: InfraStack/sampleLambda/ServiceRole/DefaultPolicy/Resource
  sampleLambdaBA9DE42C:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersba0600282c249c25d434359e221c9c9a2f78bdd225c235c3d85d8385b3937121S3BucketDE2728B6
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersba0600282c249c25d434359e221c9c9a2f78bdd225c235c3d85d8385b3937121S3VersionKey8B6F1E95
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersba0600282c249c25d434359e221c9c9a2f78bdd225c235c3d85d8385b3937121S3VersionKey8B6F1E95
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - sampleLambdaServiceRole07311550
          - Arn
      Runtime: nodejs10.x
      Environment:
        Variables:
          ENV: local
      Timeout: 60
    DependsOn:
      - sampleLambdaServiceRoleDefaultPolicy8C711846
      - sampleLambdaServiceRole07311550
    Metadata:
      aws:cdk:path: InfraStack/sampleLambda/Resource
      aws:asset:path: /Users/k.kouhei/job/give-coins/packages/infra/src/lambda/sample
      aws:asset:property: Code
  sampleApi5ADE3C70:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: sampleApi
    Metadata:
      aws:cdk:path: InfraStack/sampleApi/Resource
  sampleApiCloudWatchRole156083DB:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: InfraStack/sampleApi/CloudWatchRole/Resource
  sampleApiAccount9E165A5B:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - sampleApiCloudWatchRole156083DB
          - Arn
    DependsOn:
      - sampleApi5ADE3C70
    Metadata:
      aws:cdk:path: InfraStack/sampleApi/Account
  sampleApiDeploymentE4EE58DB8b183a5ebb4fa4fb67518fa216c9dbab:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: sampleApi5ADE3C70
      Description: Automatically created by the RestApi construct
    DependsOn:
      - sampleApisamplesGETE30FB915
      - sampleApisamplesA7D89B89
    Metadata:
      aws:cdk:path: InfraStack/sampleApi/Deployment/Resource
  sampleApiDeploymentStageprod2E32EC5B:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: sampleApi5ADE3C70
      DeploymentId:
        Ref: sampleApiDeploymentE4EE58DB8b183a5ebb4fa4fb67518fa216c9dbab
      StageName: prod
    Metadata:
      aws:cdk:path: InfraStack/sampleApi/DeploymentStage.prod/Resource
  sampleApisamplesA7D89B89:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - sampleApi5ADE3C70
          - RootResourceId
      PathPart: samples
      RestApiId:
        Ref: sampleApi5ADE3C70
    Metadata:
      aws:cdk:path: InfraStack/sampleApi/Default/samples/Resource
  sampleApisamplesGETApiPermissionInfraStacksampleApiF828075BGETsamplesA952E5D3:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - sampleLambdaBA9DE42C
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: sampleApi5ADE3C70
            - /
            - Ref: sampleApiDeploymentStageprod2E32EC5B
            - /GET/samples
    Metadata:
      aws:cdk:path: InfraStack/sampleApi/Default/samples/GET/ApiPermission.InfraStacksampleApiF828075B.GET..samples
  sampleApisamplesGETApiPermissionTestInfraStacksampleApiF828075BGETsamplesA7D12509:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - sampleLambdaBA9DE42C
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: sampleApi5ADE3C70
            - /test-invoke-stage/GET/samples
    Metadata:
      aws:cdk:path: InfraStack/sampleApi/Default/samples/GET/ApiPermission.Test.InfraStacksampleApiF828075B.GET..samples
  sampleApisamplesGETE30FB915:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId:
        Ref: sampleApisamplesA7D89B89
      RestApiId:
        Ref: sampleApi5ADE3C70
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - sampleLambdaBA9DE42C
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: InfraStack/sampleApi/Default/samples/GET/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.67.0,@aws-cdk/assets=1.67.0,@aws-cdk/aws-apigateway=1.67.0,@aws-cdk/aws-applicationautoscaling=1.67.0,@aws-cdk/aws-autoscaling-common=1.67.0,@aws-cdk/aws-cloudwatch=1.67.0,@aws-cdk/aws-codeguruprofiler=1.67.0,@aws-cdk/aws-dynamodb=1.67.0,@aws-cdk/aws-ec2=1.67.0,@aws-cdk/aws-events=1.67.0,@aws-cdk/aws-iam=1.67.0,@aws-cdk/aws-kms=1.67.0,@aws-cdk/aws-lambda=1.67.0,@aws-cdk/aws-logs=1.67.0,@aws-cdk/aws-s3=1.67.0,@aws-cdk/aws-s3-assets=1.67.0,@aws-cdk/aws-sqs=1.67.0,@aws-cdk/aws-ssm=1.67.0,@aws-cdk/cloud-assembly-schema=1.67.0,@aws-cdk/core=1.67.0,@aws-cdk/custom-resources=1.67.0,@aws-cdk/cx-api=1.67.0,@aws-cdk/region-info=1.67.0,jsii-runtime=node.js/v10.21.0
    Metadata:
      aws:cdk:path: InfraStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Parameters:
  AssetParametersba0600282c249c25d434359e221c9c9a2f78bdd225c235c3d85d8385b3937121S3BucketDE2728B6:
    Type: String
    Description: S3 bucket for asset "ba0600282c249c25d434359e221c9c9a2f78bdd225c235c3d85d8385b3937121"
  AssetParametersba0600282c249c25d434359e221c9c9a2f78bdd225c235c3d85d8385b3937121S3VersionKey8B6F1E95:
    Type: String
    Description: S3 key for asset version "ba0600282c249c25d434359e221c9c9a2f78bdd225c235c3d85d8385b3937121"
  AssetParametersba0600282c249c25d434359e221c9c9a2f78bdd225c235c3d85d8385b3937121ArtifactHash586EC4A7:
    Type: String
    Description: Artifact hash for asset "ba0600282c249c25d434359e221c9c9a2f78bdd225c235c3d85d8385b3937121"
Outputs:
  sampleApiEndpoint5CD177F1:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: sampleApi5ADE3C70
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: sampleApiDeploymentStageprod2E32EC5B
          - /
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

